[build]
  publish = "public"
  command = "yarn run build"
[build.environment]
  YARN_VERSION = "1.7.0"

[[redirects]]
  from = "/ns-chat"
  to = "https://www.meetingbird.com/h/rajk"
  status = 200

[[redirects]]
  from = "/meet"
  to = "https://www.meetingbird.com/l/rajk/meet"
  status = 302

[[redirects]]
  from = "/chat"
  to = "https://www.meetingbird.com/l/rajk/ns-friends"
  status = 302
  
  [[redirects]]
  from = "/wa"
  to = "http://wa.me/919673374334"
  status = 302
  
  [[redirects]]
  from = "/ig"
  to = "http://instagram.com/kunksed"
  status = 302
  
  [[redirects]]
  from = "/twtr"
  to = "http://twitter.com/kunksed"
  status = 302
