[build]
  publish = "public"
  command = "yarn run build"
[build.environment]
  YARN_VERSION = "1.7.0"

[[redirects]]
  from = "/ns-chat"
  to = "https://www.meetingbird.com/h/rajk"
  status = 200

[[redirects]]
  from = "/chat"
  to = "https://calendly.com/kunksed/chat"
  status = 302
  
[[redirects]]
  from = "/team"
  to = "https://calendly.com/kunksed/stoateam"
  status = 302
  
[[redirects]]
  from = "/stoa"
  to = " https://calendly.com/kunksed/stoa"
  status = 302
  
  [[redirects]]
  from = "/wa"
  to = "http://wa.me/919673374334"
  status = 302
  
  [[redirects]]
  from = "/ig"
  to = "http://instagram.com/kunksed"
  status = 302
  
  [[redirects]]
  from = "/zoom"
  to = "https://us04web.zoom.us/j/3071093231?pwd=UzhWQjdpSVRMNW5yUVIydkd1ZGhTUT09"
  status = 302
